name: Get latest polyfill.io version
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  get-latest-polyfill-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch Polyfill version
        run: |
          curl -sL https://api.github.com/repos/Financial-Times/polyfill-service/releases/latest | \
          jq -r ".tag_name" | cut -c2- > polyfill-version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Polyfill Version Bot'
          git config --global user.email 'robot@users.noreply.github.com'
          git commit -am "New version"
          git push